language: java
dist: xenial
services:
  - xvfb
addons:
  firefox: "latest"
script: mvn clean test
before_install:
  - chmod +x /home/travis/build/vaninatobar/AutomationEntregafinal/src/resources/geckodriver
